### ISSUE TITLE
请尊重Github的平台本质

### ISSUE THREAD

**Issue by Hipple** [renjie-feng-trash/fengrenjie#22]

**Comment by Hipple** [comment]
GitHub是通过Git进行版本控制的软件源代码托管服务平台

**Comment by Hipple** [comment]
GitHub是通过Git进行版本控制的软件源代码托管服务平台

绕过国内监管有很多方式，Twitter、Facebook才是这个repo该去的地方
拿这些东西上来破坏平台本质和氛围与作恶有何区别？以作恶谴责作恶，不觉得可笑么

**Comment by lizeyan** [comment]
> GitHub是通过Git进行版本控制的软件源代码托管服务平台
> 
> 绕过国内监管有很多方式，Twitter、Facebook才是这个repo该去的地方
> 拿这些东西上来破坏平台本质和氛围与作恶有何区别？以作恶谴责作恶，不觉得可笑么

GitHub也不只是只能托管源代码的。这种行为能叫作恶么？

**Comment by Hipple** [comment]
> > GitHub是通过Git进行版本控制的软件源代码托管服务平台
> > 绕过国内监管有很多方式，Twitter、Facebook才是这个repo该去的地方
> > 拿这些东西上来破坏平台本质和氛围与作恶有何区别？以作恶谴责作恶，不觉得可笑么
> 
> GitHub也不只是只能托管源代码的。这种行为能叫作恶么？

我们可以去发掘平台的其他作用价值，但这里本质仍然是程序员交流学习的地方，我们不应该让它成为负能量的集散地

**Comment by chemineau** [comment]
> > GitHub是通过Git进行版本控制的软件源代码托管服务平台
> > 绕过国内监管有很多方式，Twitter、Facebook才是这个repo该去的地方
> > 拿这些东西上来破坏平台本质和氛围与作恶有何区别？以作恶谴责作恶，不觉得可笑么
> 
> GitHub也不只是只能托管源代码的。GitHub提供了一个平台，用来做什么就不需要其他用户来限定了。我觉得只要没有散布虚假信息，在这里公开一些资料怎么能叫作恶呢？

一个单身男谈恋爱脚踏多条船引发的破事。。。如果他不配作老师可以去工作单位告他，貌似他已经被解聘了。如果涉嫌违法也可以起诉他。如果是为了进一步彻底搞臭一个人在一个专业平台上发这种东西，那就叫作恶了。

**Comment by mushrup** [comment]
既然大家这么反对，repo主不如顺便写一个pua语言探测器了放在repo里面，把这个fig的directory当作user case，看他们还反对吗？

**Comment by Hipple** [comment]
> 既然大家这么反对，repo主不如顺便写一个pua语言探测器了放在repo里面，把这个fig的directory当作user case，看他们还反对吗？

不如您来写一个，很期待

**Comment by Iydon** [comment]
请参考 [Issues 重复](https://github.com/renjie-feng-trash/fengrenjie/issues/34)。
