### ISSUE TITLE
delete

### ISSUE THREAD

**Issue by zerollzeng** [renjie-feng-trash/fengrenjie#25]

**Comment by hyfc** [comment]
[https://help.github.com/en/github/site-policy/github-acceptable-use-policies](GitHub Acceptable Use Policies)
This repo doesn't seem to violate any site policy. If you feel offended, just walk away.

**Comment by zerollzeng** [comment]
emmm... since you refer to use policies
![image](https://user-images.githubusercontent.com/38289304/70776935-75290800-1db9-11ea-97b5-5f517c61fc5f.png)

**Comment by hyfc** [comment]
It's not for you or me to say if this is discriminatory or abusive (in my opinion it's not).
If any violation really happened, the Github team will take action to it (like what they did to the Zhao-family repo). But before that, let's not play vigilantes here.

**Comment by zerollzeng** [comment]
I already issued and abuse report to github. I respect the author's right of freedom of expression and I condemn feng's behaviors too, but this repo's content is inappropriate post in github. please understand.

**Comment by iydon** [comment]
请参考 [Issues 重复](https://github.com/renjie-feng-trash/fengrenjie/issues/34)。
