### ISSUE TITLE
请不要污染这片圣地

### ISSUE THREAD

**Issue by quanzaiyu** [renjie-feng-trash/fengrenjie#31]
我也是想不明白了，这种项目居然能够上 GitHub Trending，毕竟这是代码的世界，不适合发布这种项目，要发布到社交媒体发布啊，怕国内封去Facebook啊，这得是见鬼了，越来越没有含金量，什么乱七八糟什么奇葩的项目都有，房地产的、刷题的、水的，现在连这种狗屁的都上 GitHub Trending。真希望微软做个审核，最好再加个举报功能。你做做私有项目没人说你，做成公开项目就不合适了。

**Comment by GuoweiHuang** [comment]
github怎么就成了圣地了？一个公开的可git的云盘正适合这种全网搜证的业务。

**Comment by Iydon** [comment]
@quanzaiyu 说得

**Comment by Iydon** [comment]
请参考 [Issues 重复](https://github.com/renjie-feng-trash/fengrenjie/issues/34)。

**Comment by cjim8889** [comment]
呵呵，Github并不限制必须是代码

**Comment by ZHANGneuro** [comment]
谁说github必须全是代码了，真的有贡献代码的心，除了folk别人的代码，自己多写一点有价值的东西。

**Comment by renjie-feng-trash** [comment]
Interesting...
