### ISSUE TITLE
Issues 重复

### ISSUE THREAD

**Issue by iydon** [renjie-feng-trash/fengrenjie#34]
[Issues](https://github.com/renjie-feng-trash/fengrenjie/issues) 重复内容过多，建议将是否应该使用 Git 做“新闻”的版本控制的问题放在一个 Issue 下面讨论（选择性关闭 Issues）。

注意到部分人评价主观倾向略重，通过叙述方式及账户信息可以看出，此类人使用 GitHub 时间偏少（对编程社区关注较少），可能由知乎导流而来（娱乐向较多，注我本人由 GitHub 首页才了解本次事件）。虽然 GitHub Policy 未对回答或 Issues 随意进行声明规范（或者有，我没有发现），但为保证信息的有效及简洁，请在提出 Issue 或讨论前对自己的语言进行三思。

其他 Issues 还存在以下问题（欢迎补充）：
- 格式方面：
	- 将 Issue 全部信息放在题目，而正文置空；
	- Markdown 语法使用错误（链接等）；
	- 中英文混排不规范，建议参考[中文文案排版指北](https://github.com/sparanoid/chinese-copywriting-guidelines/blob/master/README.zh-CN.md)。
- 功能方面：
	- 将 Issues 当作论坛闲聊使用，对无法删除表示不满；
	- 忽略问题编辑功能，在 Issue 下面发布修正信息。

如果您反对或支持本 Issue 的观点，仅在正文部分添加 Emoji（:thumbsdown:，:thumbsup: 等）即可，无需通过回复表示自己的态度。浏览之前 Issues 发现所贴 Emoji 只有以上所提到的两个，估计受知乎影响将赞成与反对简单映射到这两个 Emoji 了（也无不可）。

**Comment by renjie-feng-trash** [comment]
谢谢建议，此repo并不是专门面向程序员的

**Comment by quanzaiyu** [comment]
刚收到邮件才知道我的issue被删了，从这个项目的成员看，大都不是程序员圈子的，而是从知乎等平台引流过来的，在此平台上发布这种信息很是气愤，删除相关issue更是可恶。

怪不得人家国外的开发者吐槽，这都是国内一些xx项目引起的反感，不光国外，国内也对此行为非常厌恶，活生生把一个代码托管平台搞得不伦不类。

希望国家的墙再高一点，反正能进的还是能进，减少此类repo的出现。

以下是我收到的邮件：

![image](https://user-images.githubusercontent.com/13745132/70858772-58204080-1f43-11ea-87a5-e345b837ee7b.png)

![image](https://user-images.githubusercontent.com/13745132/70858775-5e162180-1f43-11ea-9593-9f19d084fb78.png)
